// @flow
export const TOGGLE_SIDEBAR_VISIBILITY = 'TOGGLE_SIDEBAR_VISIBILITY';
export const TOGGLE_SIDEBAR_COLLAPSED = 'TOGGLE_SIDEBAR_COLLAPSED';
export const CHANGE_PRIMARY_COLOR = 'CHANGE_PRIMARY_COLOR';
export const CHANGE_THEME = 'CHANGE_THEME';
